# VS Code with declarative-but-live configuration, adapted from
# fersilva16/nix-config: extensions come from the full Marketplace via
# nix-vscode-extensions, the extensions dir stays mutable so UI installs keep
# working (promote them with `vscode-sync-extensions`), and settings.json is
# an out-of-store symlink into this repo so UI edits write straight back here
# and survive rebuilds.
{
  config,
  flake,
  lib,
  pkgs,
  ...
}:
let
  configDir =
    if pkgs.stdenv.isDarwin then "Library/Application Support/Code/User" else ".config/Code/User";

  marketplace =
    flake.inputs.nix-vscode-extensions.extensions.${pkgs.stdenv.hostPlatform.system}.vscode-marketplace;

  # Resolve a "publisher.name" ID to its Marketplace package. Some IDs are
  # missing on a given platform (licensing, removals) and throw at eval, so
  # tryEval and drop them with a warning — they keep working as manual
  # installs thanks to mutableExtensionsDir.
  resolve =
    id:
    let
      parts = lib.splitString "." id;
      publisher = builtins.head parts;
      name = lib.concatStringsSep "." (builtins.tail parts);
      attempt = builtins.tryEval (
        let
          extension = marketplace.${publisher}.${name};
        in
        builtins.seq (extension.type or null) extension
      );
    in
    if attempt.success then attempt.value else null;

  declaredIds = import ./extensions.nix;
  unavailableIds = builtins.filter (id: resolve id == null) declaredIds;
  extensions =
    lib.warnIf (unavailableIds != [ ])
      "vscode: skipping extensions unavailable on ${pkgs.stdenv.hostPlatform.system} (still installable manually): ${lib.concatStringsSep ", " unavailableIds}"
      (builtins.filter (extension: extension != null) (map resolve declaredIds));

  # Snapshot the live extension set (declared + UI installs) back into
  # extensions.nix, so the declared list matches reality after installing
  # freely from the Marketplace UI.
  syncExtensions = pkgs.writeShellScriptBin "vscode-sync-extensions" ''
    set -euo pipefail

    repo="''${VSCODE_NIX_REPO:-$HOME/www/nixcfg}"
    out="$repo/home/noghartt/features/vscode/extensions.nix"

    code_bin="$(command -v code || true)"
    if [ -z "$code_bin" ]; then
      code_bin="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    fi
    if [ ! -x "$code_bin" ]; then
      echo "vscode-sync-extensions: could not find the 'code' CLI" >&2
      exit 1
    fi

    tmp="$(mktemp)"
    {
      echo "# Generated by vscode-sync-extensions — do not edit by hand."
      echo "# Install freely from the Marketplace UI, then run"
      echo "# vscode-sync-extensions and rebuild to make it reproducible."
      echo "["
      "$code_bin" --list-extensions | sort -u | while IFS= read -r ext; do
        [ -z "$ext" ] && continue
        printf '  "%s"\n' "$ext"
      done
      echo "]"
    } > "$tmp"

    ${pkgs.nixfmt}/bin/nixfmt "$tmp" >/dev/null 2>&1 || true
    mv "$tmp" "$out"

    echo "vscode-sync-extensions: wrote $out"
  '';
in
{
  home.packages = [
    syncExtensions
    # Referenced by settings.json for the Nix language server and formatter.
    pkgs.nixd
    pkgs.nixfmt
  ];

  programs.vscode = {
    enable = true;
    mutableExtensionsDir = true;
    profiles.default.extensions = extensions;
  };

  # Nix-first but live-writable settings; assumes the flake checkout lives at
  # ~/www/nixcfg.
  home.file."${configDir}/settings.json".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/www/nixcfg/home/noghartt/features/vscode/settings.json";
}
