# Generated by vscode-sync-extensions — do not edit by hand.
# Install freely from the Marketplace UI, then run
# vscode-sync-extensions and rebuild to make it reproducible.
[
  "editorconfig.editorconfig"
  "jnoortheen.nix-ide"
  "mkhl.direnv"
]
